//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestorLibrosEntityAjax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tlineafactura
    {
        public int IDLinea { get; set; }
        public int CodFactura { get; set; }
        public int CodLibro { get; set; }
        public string Cantidad { get; set; }
        public string Total { get; set; }
    
        public virtual tfactura tfactura { get; set; }
        public virtual tlibro tlibro { get; set; }
    }
}
